#!/bin/bash
# kpassman - a password manager that uses gpg to encrypt and decrypt stored passwords and uses kdialog to provide a GUI.
# Written by simonizor https://www.simonizor.gq
# Dependencies: gpg, xclip, kdialog, apg (optional - for generating passwords)
# License: GPL v2 Only

REALPATH="$(readlink -f $0)"
RUNNING_DIR="$(dirname "$REALPATH")"

if [ -f "$RUNNING_DIR/pydialog/pydialog.py" ]; then
    KDIALOG="$RUNNING_DIR/pydialog/pydialog.py"
else
    KDIALOG='kdialog'
fi

addpassfunc () {
    SERVICE_NAME="$($KDIALOG --title "kpassman" --inputbox "<h2 align="center">kpassman</h2><h2 align="center"><img src='/opt/kpassman/kpassman.png' width=50></h2><h4 align="center">Input the name for the password:</h4>")"
    case $? in
        1)
            mainfunc
            ;;
    esac
    if [ -z "$SERVICE_NAME" ]; then
        $KDIALOG --title "kpassman" --error "No name was entered!"
        mainfunc
    fi
    if [ -f "$KPASS_DIR/$SERVICE_NAME/$SERVICE_NAME.gpg" ]; then
        $KDIALOG --title "kpassman" --error "$SERVICE_NAME already exists!\nRemove $SERVICE_NAME before adding a new password for $SERVICE_NAME."
        mainfunc
    fi
    PASS_INPUT1="$($KDIALOG --title "kpassman" --password "Enter your password for $SERVICE_NAME:")"
    case $? in
        1)
            mainfunc
            ;;
    esac
    PASS_INPUT2="$($KDIALOG --title "kpassman" --password "Enter your password $SERVICE_NAME again:")"
    case $? in
        1)
            mainfunc
            ;;
    esac
    if [ "$PASS_INPUT1" != "$PASS_INPUT2" ]; then
        $KDIALOG --title "kpassman" --error "Passwords do not match!"
        mainfunc
    fi
    if [ ! -d "$KPASS_DIR/$SERVICE_NAME" ]; then
        mkdir "$KPASS_DIR"/"$SERVICE_NAME"
    fi
    $KDIALOG --title "kpassman" --msgbox "Enter the password to be used for encrypting and decrypting the stored password for $SERVICE_NAME in the next window."
    echo "$PASS_INPUT1" | gpg --no-tty -c -o "$KPASS_DIR"/"$SERVICE_NAME"/"$SERVICE_NAME".gpg
    if [ -f "$KPASS_DIR/$SERVICE_NAME/$SERVICE_NAME.gpg" ]; then
        $KDIALOG --title "kpassman" --msgbox "Password for $SERVICE_NAME was stored!"
    else
        rm -r "$KPASS_DIR"/"$SERVICE_NAME"
        $KDIALOG --title "kpassman" --error "Error storing password for $SERVICE_NAME!"
    fi
    mainfunc
}

passclearfunc () {
    sleep 45
    echo -n "Password cleared from clipboard" | xclip -selection c -i
    notify-send "kpassman" "Password for $SERVICE_NAME cleared from clipboard." || $KDIALOG --msgbox "Password for $SERVICE_NAME cleared from clipboard!"
}

decryptpassfunc () {
    SERVICE_NAME="$($KDIALOG --title "kpassman" --combobox "<h2 align="center">kpassman</h2><h2 align="center"><img src='/opt/kpassman/kpassman.png' width=50></h2><h4 align="center">Select a password to decrypt:</h4>" $(dir -C -w 1 $KPASS_DIR))"
    case $? in
        1)
            mainfunc
            ;;
    esac
    if [ -z "$SERVICE_NAME" ]; then
        $KDIALOG --title "kpassman" --error "No selection made!"
        mainfunc
    fi
    echo -n "$(gpg --no-tty -d "$KPASS_DIR"/"$SERVICE_NAME"/"$SERVICE_NAME".gpg)" | xclip -selection c -i
    if [ "$(xclip -selection c -o)" = "" ]; then
        $KDIALOG --title "kpassman" --error "Wrong password or gpg failure!"
        mainfunc
    fi
    notify-send "kpassman" "Password for $SERVICE_NAME copied to clipboard for 45 seconds." || $KDIALOG --msgbox "Password for $SERVICE_NAME has been copied to clipboard!  Clipboard will be cleared in 45 seconds."
    passclearfunc &
    mainfunc
}

backupfunc () {
    BACKUP_DIR="$($KDIALOG --title "kpassman" --getexistingdirectory "$HOME")"
    case $? in
        1)
            mainfunc
            ;;
    esac
    if [ ! -d "$BACKUP_DIR" ]; then
        $KDIALOG --title "kpassman" --error "Error finding directory!"
        mainfunc
    fi
    cp -r "$KPASS_DIR"/* "$BACKUP_DIR"/ && $KDIALOG --title "kpassman" --msgbox "Passwords backed up to $BACKUP_DIR!" || $KDIALOG --title "kpassman" --error "Error backing up passwords!"
    mainfunc
}

removepassfunc () {
    SERVICE_NAME="$($KDIALOG --title "kpassman" --combobox "<h2 align="center">kpassman</h2><h2 align="center"><img src='/opt/kpassman/kpassman.png' width=50></h2><h4 align="center">Select a password to remove:</h4>" $(dir -C -w 1 $KPASS_DIR))"
    case $? in
        1)
            mainfunc
            ;;
    esac
    if [ -z "$SERVICE_NAME" ]; then
        $KDIALOG --title "kpassman" --error "No selection made!"
        mainfunc
    fi
    echo -n "$(gpg --no-tty -d "$KPASS_DIR"/"$SERVICE_NAME"/"$SERVICE_NAME".gpg)" | xclip -selection c -i
    if [ "$(xclip -selection c -o)" = "" ]; then
        $KDIALOG --title "kpassman" --error --text "Wrong password or gpg failure!"
        mainfunc
    fi
    echo "Password cleared from clipboard" | xclip -selection c -i
    $KDIALOG --title "kpassman" --warningyesno "Are you sure you want to delete the stored password for $SERVICE_NAME?"
    case $? in
        0)
            rm -r "$KPASS_DIR"/"$SERVICE_NAME"/
            $KDIALOG --title "kpassman" --msgbox "Password for $SERVICE_NAME was removed!"
            mainfunc
            ;;
        1)
            $KDIALOG --title "kpassman" --msgbox "Password for $SERVICE_NAME was not removed."
            mainfunc
            ;;
    esac
}

apgpassgenfunc () {
    PASSGEN="$($KDIALOG --title "kpassman" --combobox "<h2 align="center">kpassman</h2><h2 align="center"><img src='/opt/kpassman/kpassman.png' width=50></h2><h4 align="center">Select a password to copy to your clipboard:</h4>" $(apg -a 1 -m 30 -n 10))"
    case $? in
        0)
            echo -n "$PASSGEN" | xclip -selection c -i
            mainfunc
            ;;
        1)
            mainfunc
            ;;
    esac
}

if [ -d "$HOME/.gpgpassman" ] && [ ! -f "$HOME/.kpassman/.kpassman.config" ]; then
    KPASS_DIR="$HOME/.gpgpassman"
    echo "KPASS_DIR="\"$KPASS_DIR\""" > "$KPASS_DIR"/.kpassman.config
elif [ -d "$HOME/.kpassman" ] && [ ! -f "$HOME/.kpassman/.kpassman.config" ]; then
    KPASS_DIR="$HOME/.kpassman"
    echo "KPASS_DIR="\"$KPASS_DIR\""" > "$KPASS_DIR"/.kpassman.config
else
    mkdir "$HOME"/.kpassman
    KPASS_DIR="$HOME/.kpassman"
    echo "KPASS_DIR="\"$KPASS_DIR\""" > "$KPASS_DIR"/.kpassman.config
fi
. "$KPASS_DIR"/.kpassman.config
mainfunc () {
    KPASS_START="$($KDIALOG --title "kpassman" --combobox "<h2 align="center">kpassman</h2><h2 align="center"><img src='/opt/kpassman/kpassman.png' width=50></h2><h4 align="center">Welcome to kpassman</h4><h4 align="center">Select an option below:</h4>" "Add a new encrypted password" "Decrypt a stored password" "Backup your stored passwords" "Remove a stored password" "Generate passwords using apg")"
    case $? in
        1)
            exit 0
            ;;
    esac
    case $KPASS_START in
        Add*)
            addpassfunc
            exit 0
            ;;
        Decrypt*)
            decryptpassfunc
            exit 0
            ;;
        Backup*)
            backupfunc
            exit 0
            ;;
        Remove*)
            removepassfunc
            exit 0
            ;;
        Generate*)
            apgpassgenfunc
            exit 0
            ;;
        *)
            exit 0
            ;;
    esac
}
mainfunc
